### ISSUE TITLE
Change permisions of certificates

### ISSUE THREAD

**Issue by Casburggraaf** [bjornsnoen/minica-api#2]
Is there a way to set the UID GUID of the files that are generated? I'm using the files for traefik, that works without problems. But i'm also using the certs/keys for developments tools(nodeJS). Only node wont work because the files are root:root
Is there a (easy) fix for this?

**Comment by bjornsnoen** [comment]
There isn't an easy fix for that right now, but I will try adding some env vars that should let you hard code the uid:gid you want, just need to make sure it doesn't break anything.

**Comment by Casburggraaf** [comment]
That would be great. I tried setting the "user:" but then i get this error
```
minica  | Error: Can't drop privilege as nonroot user
minica  | For help, use .venv/bin/supervisord -h
```
I like the way the Linuxserver is giving the option in a -e (as example https://hub.docker.com/r/linuxserver/syncthing)

**Comment by bjornsnoen** [comment]
I pushed a new version that has this feature implemented via env vars `USER_ID` and `GROUP_ID`, would you mind checking that this works for you @Casburggraaf?

**Comment by Casburggraaf** [comment]
It works fine! Thank you for the quick update

**Comment by bjornsnoen** [comment]
Not at all, happy to be able to help :blush:

**Comment by theodejager** [comment]
Hi! Is there a way to also set the USER_ID and GROUP_ID of the key.pem file, not only the cert.pem?
