### ISSUE TITLE
Support for routes in config file

### ISSUE THREAD

**Issue by Casburggraaf** [bjornsnoen/minica-api#5]
First of all, still loving this service, using it with a lot of love,

Is there a way to generate certs of routes that are declared in traefik with the  File Provider.
I have some no non docker applications that i use. I now use the curl api for generating but would love that this can be automatic.

**Comment by bjornsnoen** [comment]
Hi! Glad to hear it's useful. I also use the api for this, but I suppse there's no reason not to add support for adding it via config. Would a basic yaml file listing the domains mounted into the container suffice?

**Comment by Casburggraaf** [comment]
Best case scenario would be on startup or cron run the  /api/http/routers endpoint and math if all routes/hotst have a cert. But don't know of that would be possible

**Comment by bjornsnoen** [comment]
@Casburggraaf sorry I don't really understand the use case. It sounds like the routes you want certs for are already defined somewhere, minica-api just doesn't know about it. Could you paste a docker-compose.yml file (plus whatever other files are important) that shows what you want to work?

**Comment by bjornsnoen** [comment]
Closing for now, feel free to reopen with clear description of the feature you'd like to see implemented
